//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieID { get; set; }
        public string Title { get; set; }
        public int VoteCount { get; set; }
        public bool IsOwned { get; set; }
        public string Year { get; set; }
        public string SortString { get; set; }
        public int TMDbID { get; set; }
    }
}
